name: '部屬後端專案'
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/network-dashboard-api # 使用你的 Docker Hub 使用者名稱和應用程式名稱。
      - name: 更新 known_hosts 文件 # 步驟的名稱
        run: | # 將要執行的命令
          mkdir -p ~/.ssh  
          ssh-keyscan ${{ secrets.HOST_NAME }} >> ~/.ssh/known_hosts
      # 請將 'hostname' 替換為你的服務器地址，例如 IP 地址或域名
      - name: Deploy to Docker
        run: |
          ssh root@${{ secrets.HOST_NAME }} '
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/network-dashboard-api
            docker rm -f network-dashboard-api || true
            docker run -d -p 4000:4000 --name network-dashboard-api ${{ secrets.DOCKER_HUB_USERNAME }}/network-dashboard-api
          '
